import { Bell, Filter, RefreshCw, Globe, MapPin, Megaphone, AlertTriangle, Clock, FileText } from 'lucide-react';
import { Button } from './ui/button';
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from './ui/sheet';
import { Badge } from './ui/badge';
import { ScrollArea } from './ui/scroll-area';
import { Separator } from './ui/separator';
import { formatDistanceToNow } from 'date-fns';
import { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';

// Database notification interface
interface DBNotification {
  id: string;
  title: string;
  message: string;
  type: 'SURVEY_CREATED' | 'SURVEY_UPDATED' | 'MASTER_DATA_UPDATED' | 'ANNOUNCEMENT' | 'ALERT' | 'REMINDER';
  scope: 'GLOBAL' | 'ACI';
  aci_id: number | null;
  priority: 'low' | 'normal' | 'high';
  isAutoGenerated: boolean;
  createdBy: { userId: string; role: string; name: string };
  createdAt: string;
  validFrom: string;
  validTill: string | null;
}

const typeColors: Record<string, string> = {
  SURVEY_CREATED: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
  SURVEY_UPDATED: 'bg-indigo-500/10 text-indigo-500 border-indigo-500/20',
  MASTER_DATA_UPDATED: 'bg-purple-500/10 text-purple-500 border-purple-500/20',
  ANNOUNCEMENT: 'bg-green-500/10 text-green-500 border-green-500/20',
  ALERT: 'bg-red-500/10 text-red-500 border-red-500/20',
  REMINDER: 'bg-yellow-500/10 text-yellow-500 border-yellow-500/20',
};

const priorityColors: Record<string, string> = {
  low: 'bg-gray-100 text-gray-600',
  normal: 'bg-blue-100 text-blue-600',
  high: 'bg-red-100 text-red-600',
};

const getTypeIcon = (type: string) => {
  switch (type) {
    case 'SURVEY_CREATED':
    case 'SURVEY_UPDATED':
      return <FileText className="h-4 w-4" />;
    case 'ANNOUNCEMENT':
      return <Megaphone className="h-4 w-4" />;
    case 'ALERT':
      return <AlertTriangle className="h-4 w-4" />;
    case 'REMINDER':
      return <Clock className="h-4 w-4" />;
    default:
      return <Bell className="h-4 w-4" />;
  }
};

export const NotificationCenter = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [notifications, setNotifications] = useState<DBNotification[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [filter, setFilter] = useState<'all' | 'announcements' | 'surveys'>('all');
  const [isOpen, setIsOpen] = useState(false);

  const canAccessNotifications = user && ['L0', 'L1', 'L2'].includes(user.role);

  const fetchNotifications = useCallback(async () => {
    if (!canAccessNotifications) return;
    setLoading(true);
    setError(null);
    try {
      const response = await fetch('/api/admin/notifications?limit=20', { credentials: 'include' });
      if (!response.ok) throw new Error('Failed to fetch notifications');
      const data = await response.json();
      if (data.success && data.data?.notifications) {
        setNotifications(data.data.notifications);
      }
    } catch (err) {
      console.error('Error fetching notifications:', err);
      setError('Failed to load notifications');
    } finally {
      setLoading(false);
    }
  }, [canAccessNotifications]);

  useEffect(() => {
    if (isOpen && canAccessNotifications) fetchNotifications();
  }, [isOpen, fetchNotifications, canAccessNotifications]);

  useEffect(() => {
    if (canAccessNotifications) fetchNotifications();
  }, [canAccessNotifications, fetchNotifications]);

  const filteredNotifications = notifications.filter((n) => {
    if (filter === 'announcements') return ['ANNOUNCEMENT', 'ALERT', 'REMINDER'].includes(n.type);
    if (filter === 'surveys') return ['SURVEY_CREATED', 'SURVEY_UPDATED'].includes(n.type);
    return true;
  });

  const announcementCount = notifications.filter((n) => ['ANNOUNCEMENT', 'ALERT', 'REMINDER'].includes(n.type)).length;
  const surveyCount = notifications.filter((n) => ['SURVEY_CREATED', 'SURVEY_UPDATED'].includes(n.type)).length;

  if (!canAccessNotifications) {
    return (
      <Button variant="ghost" size="icon" className="relative opacity-50" disabled>
        <Bell className="h-5 w-5" />
      </Button>
    );
  }

  const spinClass = loading ? 'animate-spin' : '';

  return (
    <Sheet open={isOpen} onOpenChange={setIsOpen}>
      <SheetTrigger asChild>
        <Button variant="ghost" size="icon" className="relative">
          <Bell className="h-5 w-5" />
          {notifications.length > 0 && (
            <Badge className="absolute -top-1 -right-1 h-5 w-5 flex items-center justify-center p-0 text-xs" variant="destructive">
              {notifications.length > 9 ? '9+' : notifications.length}
            </Badge>
          )}
        </Button>
      </SheetTrigger>
      <SheetContent className="w-full sm:max-w-md">
        <SheetHeader>
          <SheetTitle className="flex items-center justify-between flex-wrap gap-2">
            <span>Notifications</span>
            <Button variant="ghost" size="sm" onClick={fetchNotifications} disabled={loading} className="h-8">
              <RefreshCw className={'h-4 w-4 ' + spinClass} />
            </Button>
          </SheetTitle>
          <SheetDescription className="flex items-center gap-2 flex-wrap">
            <Filter className="h-3 w-3 flex-shrink-0" />
            <Button variant={filter === 'all' ? 'default' : 'ghost'} size="sm" onClick={() => setFilter('all')} className="h-7 text-xs">
              All ({notifications.length})
            </Button>
            <Button variant={filter === 'announcements' ? 'default' : 'ghost'} size="sm" onClick={() => setFilter('announcements')} className="h-7 text-xs">
              Announcements ({announcementCount})
            </Button>
            <Button variant={filter === 'surveys' ? 'default' : 'ghost'} size="sm" onClick={() => setFilter('surveys')} className="h-7 text-xs">
              Surveys ({surveyCount})
            </Button>
          </SheetDescription>
        </SheetHeader>
        <Separator className="my-4" />
        <ScrollArea className="h-[calc(100vh-14rem)]">
          {loading && notifications.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-40 text-center">
              <RefreshCw className="h-8 w-8 text-muted-foreground mb-2 animate-spin" />
              <p className="text-sm text-muted-foreground">Loading notifications...</p>
            </div>
          ) : error ? (
            <div className="flex flex-col items-center justify-center h-40 text-center">
              <AlertTriangle className="h-8 w-8 text-red-500 mb-2" />
              <p className="text-sm text-red-500">{error}</p>
              <Button variant="outline" size="sm" onClick={fetchNotifications} className="mt-2">Retry</Button>
            </div>
          ) : filteredNotifications.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-40 text-center">
              <Bell className="h-12 w-12 text-muted-foreground mb-2 opacity-50" />
              <p className="text-sm text-muted-foreground">No notifications</p>
            </div>
          ) : (
            <div className="space-y-2">
              {filteredNotifications.map((notification) => (
                <div key={notification.id} className="p-3 rounded-lg border bg-card hover:shadow-md transition-all">
                  <div className="flex items-start gap-3">
                    <div className={'p-2 rounded-full ' + (typeColors[notification.type] || 'bg-gray-100')}>
                      {getTypeIcon(notification.type)}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-start justify-between gap-2">
                        <h4 className="text-sm font-semibold truncate">{notification.title}</h4>
                        <Badge variant="outline" className={'text-xs ' + priorityColors[notification.priority]}>
                          {notification.priority}
                        </Badge>
                      </div>
                      <p className="text-xs text-muted-foreground mt-1 line-clamp-2">{notification.message}</p>
                      <div className="flex items-center gap-2 mt-2 flex-wrap">
                        <Badge variant="outline" className="text-xs flex items-center">
                          {notification.scope === 'GLOBAL' ? (
                            <><Globe className="h-3 w-3 mr-1" /> Global</>
                          ) : (
                            <><MapPin className="h-3 w-3 mr-1" /> AC {notification.aci_id}</>
                          )}
                        </Badge>
                        {notification.isAutoGenerated && <Badge variant="secondary" className="text-xs">Auto</Badge>}
                        <span className="text-xs text-muted-foreground">
                          {formatDistanceToNow(new Date(notification.createdAt), { addSuffix: true })}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </ScrollArea>
        <Separator className="my-4" />
        <Button variant="outline" className="w-full" onClick={() => { setIsOpen(false); navigate('/shared/notifications'); }}>
          View All Notifications
        </Button>
      </SheetContent>
    </Sheet>
  );
};
