import mongoose from "mongoose";

/**
 * Notification Schema
 * Stores notifications for booth agents (mobile app) and admin dashboard
 * Mobile backend reads from same collection to fetch notifications
 */
const notificationSchema = new mongoose.Schema(
  {
    // Creator information
    createdBy: {
      userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
      },
      role: {
        type: String,
        enum: ["L0", "L1", "L2", "SYSTEM"],
        required: true,
      },
      name: {
        type: String,
        trim: true,
      },
    },

    // Targeting
    scope: {
      type: String,
      enum: ["GLOBAL", "ACI"],
      required: true,
    },
    aci_id: {
      type: Number,
      default: null,
      // Required if scope is ACI, validated in pre-save hook
    },

    // Content
    type: {
      type: String,
      enum: [
        "SURVEY_CREATED",
        "SURVEY_UPDATED",
        "MASTER_DATA_UPDATED",
        "ANNOUNCEMENT",
        "ALERT",
        "REMINDER",
      ],
      required: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
      maxlength: 100,
    },
    message: {
      type: String,
      required: true,
      trim: true,
      maxlength: 500,
    },
    priority: {
      type: String,
      enum: ["low", "normal", "high"],
      default: "normal",
    },

    // Related entity (for auto-generated notifications)
    relatedEntity: {
      type: {
        type: String,
        enum: ["SURVEY", "MASTER_DATA", null],
      },
      id: {
        type: mongoose.Schema.Types.ObjectId,
      },
    },

    // Validity period
    validFrom: {
      type: Date,
      default: Date.now,
    },
    validTill: {
      type: Date,
      default: null,
    },

    // Metadata
    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
    deleted: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
    collection: "notifications",
    toJSON: {
      virtuals: true,
      transform: (_doc, ret) => {
        ret.id = ret._id.toString();
        delete ret._id;
        delete ret.__v;
        return ret;
      },
    },
  }
);

// Virtual for id
notificationSchema.virtual("id").get(function getId() {
  return this._id.toString();
});

// Pre-save validation
notificationSchema.pre("save", function (next) {
  // If scope is ACI, aci_id is required
  if (this.scope === "ACI" && (this.aci_id === null || this.aci_id === undefined)) {
    return next(new Error("aci_id is required when scope is ACI"));
  }

  // If scope is GLOBAL, aci_id should be null
  if (this.scope === "GLOBAL") {
    this.aci_id = null;
  }

  // Validate validTill >= validFrom if both are provided
  if (this.validTill && this.validFrom && this.validTill < this.validFrom) {
    return next(new Error("validTill must be greater than or equal to validFrom"));
  }

  next();
});

// Indexes for efficient queries
// Primary index for mobile backend queries (by scope and AC)
notificationSchema.index({ scope: 1, aci_id: 1, createdAt: -1 });

// Index for expiry queries
notificationSchema.index({ validTill: 1 });

// Index for soft delete filtering
notificationSchema.index({ deleted: 1 });

// Index for finding related notifications
notificationSchema.index({ "relatedEntity.type": 1, "relatedEntity.id": 1 });

// Compound index for admin listing with date sorting
notificationSchema.index({ deleted: 1, createdAt: -1 });

// Index for type filtering
notificationSchema.index({ type: 1, createdAt: -1 });

export default mongoose.models.Notification || mongoose.model("Notification", notificationSchema);
