import React, { useState, useEffect } from "react";
import { Bell, Plus, Trash2, Search, Filter, Send, Globe, MapPin } from "lucide-react";
import { DashboardLayout } from "@/components/DashboardLayout";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { api } from "@/lib/api";
import { useAuth } from "@/contexts/AuthContext";
import { CONSTITUENCIES } from "@/constants/constituencies";

interface Notification {
  id: string;
  createdBy: {
    userId: string;
    role: string;
    name: string;
  };
  scope: "GLOBAL" | "ACI";
  aci_id: number | null;
  type: string;
  title: string;
  message: string;
  priority: "low" | "normal" | "high";
  relatedEntity?: {
    type: string;
    id: string;
  };
  validFrom: string;
  validTill: string | null;
  isAutoGenerated: boolean;
  createdAt: string;
}

interface CreateNotificationForm {
  scope: "GLOBAL" | "ACI";
  aci_id: string;
  type: string;
  title: string;
  message: string;
  priority: string;
  validTill: string;
}

const NotificationManagement: React.FC = () => {
  const { toast } = useToast();
  const { user } = useAuth();
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState("");
  const [typeFilter, setTypeFilter] = useState<string>("all");
  const [scopeFilter, setScopeFilter] = useState<string>("all");
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const [selectedNotification, setSelectedNotification] = useState<Notification | null>(null);
  const [creating, setCreating] = useState(false);
  const [pagination, setPagination] = useState({
    total: 0,
    page: 1,
    limit: 20,
    totalPages: 1,
  });

  const [formData, setFormData] = useState<CreateNotificationForm>({
    scope: "ACI",
    aci_id: user?.assignedAC?.toString() || "",
    type: "ANNOUNCEMENT",
    title: "",
    message: "",
    priority: "normal",
    validTill: "",
  });

  const isL0 = user?.role === "L0";
  const isL1 = user?.role === "L1";

  useEffect(() => {
    fetchNotifications();
  }, [pagination.page, typeFilter, scopeFilter]);

  const fetchNotifications = async () => {
    try {
      setLoading(true);
      const params = new URLSearchParams();
      params.append("page", pagination.page.toString());
      params.append("limit", pagination.limit.toString());
      if (typeFilter !== "all") params.append("type", typeFilter);
      if (scopeFilter !== "all") params.append("scope", scopeFilter);

      const response = await api.get(`/admin/notifications?${params.toString()}`);
      setNotifications(response.data.notifications || []);
      setPagination(prev => ({
        ...prev,
        total: response.data.pagination.total,
        totalPages: response.data.pagination.totalPages,
      }));
    } catch (error: any) {
      console.error("Error fetching notifications:", error);
      toast({
        title: "Error",
        description: error.message || "Failed to fetch notifications",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const handleCreateNotification = async () => {
    if (!formData.title.trim() || !formData.message.trim()) {
      toast({
        title: "Validation Error",
        description: "Title and message are required",
        variant: "destructive",
      });
      return;
    }

    if (formData.scope === "ACI" && !formData.aci_id) {
      toast({
        title: "Validation Error",
        description: "Please select an Assembly Constituency",
        variant: "destructive",
      });
      return;
    }

    try {
      setCreating(true);
      const payload: any = {
        scope: formData.scope,
        type: formData.type,
        title: formData.title.trim(),
        message: formData.message.trim(),
        priority: formData.priority,
      };

      if (formData.scope === "ACI") {
        payload.aci_id = parseInt(formData.aci_id);
      }

      if (formData.validTill) {
        payload.validTill = new Date(formData.validTill).toISOString();
      }

      await api.post("/admin/notifications", payload);

      toast({
        title: "Success",
        description: "Notification created successfully",
      });

      setIsCreateDialogOpen(false);
      resetForm();
      fetchNotifications();
    } catch (error: any) {
      console.error("Error creating notification:", error);
      toast({
        title: "Error",
        description: error.message || "Failed to create notification",
        variant: "destructive",
      });
    } finally {
      setCreating(false);
    }
  };

  const handleDeleteNotification = async () => {
    if (!selectedNotification) return;

    try {
      await api.delete(`/admin/notifications/${selectedNotification.id}`);
      toast({
        title: "Success",
        description: "Notification deleted successfully",
      });
      setIsDeleteDialogOpen(false);
      setSelectedNotification(null);
      fetchNotifications();
    } catch (error: any) {
      console.error("Error deleting notification:", error);
      toast({
        title: "Error",
        description: error.message || "Failed to delete notification",
        variant: "destructive",
      });
    }
  };

  const resetForm = () => {
    setFormData({
      scope: isL0 ? "GLOBAL" : "ACI",
      aci_id: user?.assignedAC?.toString() || "",
      type: "ANNOUNCEMENT",
      title: "",
      message: "",
      priority: "normal",
      validTill: "",
    });
  };

  const getTypeBadgeVariant = (type: string) => {
    switch (type) {
      case "SURVEY_CREATED":
      case "SURVEY_UPDATED":
        return "default";
      case "MASTER_DATA_UPDATED":
        return "secondary";
      case "ANNOUNCEMENT":
        return "outline";
      case "ALERT":
        return "destructive";
      case "REMINDER":
        return "default";
      default:
        return "outline";
    }
  };

  const getPriorityBadgeVariant = (priority: string) => {
    switch (priority) {
      case "high":
        return "destructive";
      case "normal":
        return "default";
      case "low":
        return "secondary";
      default:
        return "outline";
    }
  };

  const getScopeBadge = (notification: Notification) => {
    if (notification.scope === "GLOBAL") {
      return (
        <Badge variant="default" className="flex items-center gap-1">
          <Globe className="h-3 w-3" />
          GLOBAL
        </Badge>
      );
    }
    const acName = CONSTITUENCIES.find(c => c.number === notification.aci_id)?.name || `AC ${notification.aci_id}`;
    return (
      <Badge variant="outline" className="flex items-center gap-1">
        <MapPin className="h-3 w-3" />
        {acName}
      </Badge>
    );
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleString("en-IN", {
      dateStyle: "medium",
      timeStyle: "short",
    });
  };

  const filteredNotifications = notifications.filter(n =>
    n.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
    n.message.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const getAvailableACs = () => {
    if (isL0) {
      return CONSTITUENCIES;
    }
    if (user?.assignedAC) {
      return CONSTITUENCIES.filter(c => c.number === user.assignedAC);
    }
    return [];
  };

  return (
    <DashboardLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <div>
            <h1 className="text-2xl font-bold flex items-center gap-2">
              <Bell className="h-6 w-6" />
              Notification Management
            </h1>
            <p className="text-muted-foreground">
              Create and manage notifications for booth agents
            </p>
          </div>
          <Button onClick={() => setIsCreateDialogOpen(true)} className="flex items-center gap-2">
            <Plus className="h-4 w-4" />
            Create Notification
          </Button>
        </div>

        {/* Filters */}
        <Card>
          <CardContent className="pt-6">
            <div className="flex flex-col sm:flex-row gap-4">
              <div className="flex-1">
                <div className="relative">
                  <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                  <Input
                    placeholder="Search notifications..."
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    className="pl-10"
                  />
                </div>
              </div>
              <div className="flex gap-2">
                <Select value={typeFilter} onValueChange={setTypeFilter}>
                  <SelectTrigger className="w-[180px]">
                    <Filter className="h-4 w-4 mr-2" />
                    <SelectValue placeholder="Filter by type" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All Types</SelectItem>
                    <SelectItem value="SURVEY_CREATED">Survey Created</SelectItem>
                    <SelectItem value="SURVEY_UPDATED">Survey Updated</SelectItem>
                    <SelectItem value="MASTER_DATA_UPDATED">Master Data Updated</SelectItem>
                    <SelectItem value="ANNOUNCEMENT">Announcement</SelectItem>
                    <SelectItem value="ALERT">Alert</SelectItem>
                    <SelectItem value="REMINDER">Reminder</SelectItem>
                  </SelectContent>
                </Select>
                <Select value={scopeFilter} onValueChange={setScopeFilter}>
                  <SelectTrigger className="w-[150px]">
                    <SelectValue placeholder="Scope" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All Scopes</SelectItem>
                    <SelectItem value="GLOBAL">Global</SelectItem>
                    <SelectItem value="ACI">AC Specific</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Notifications Table */}
        <Card>
          <CardHeader>
            <CardTitle>Notifications ({pagination.total})</CardTitle>
            <CardDescription>
              {isL0 ? "All notifications in the system" : "Notifications for your constituency"}
            </CardDescription>
          </CardHeader>
          <CardContent>
            {loading ? (
              <div className="flex justify-center py-8">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
              </div>
            ) : filteredNotifications.length === 0 ? (
              <div className="text-center py-8 text-muted-foreground">
                No notifications found
              </div>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Title</TableHead>
                    <TableHead>Type</TableHead>
                    <TableHead>Scope</TableHead>
                    <TableHead>Priority</TableHead>
                    <TableHead>Created By</TableHead>
                    <TableHead>Created At</TableHead>
                    <TableHead>Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredNotifications.map((notification) => (
                    <TableRow key={notification.id}>
                      <TableCell>
                        <div>
                          <div className="font-medium">{notification.title}</div>
                          <div className="text-sm text-muted-foreground truncate max-w-[300px]">
                            {notification.message}
                          </div>
                          {notification.isAutoGenerated && (
                            <Badge variant="outline" className="mt-1 text-xs">
                              Auto-generated
                            </Badge>
                          )}
                        </div>
                      </TableCell>
                      <TableCell>
                        <Badge variant={getTypeBadgeVariant(notification.type)}>
                          {notification.type.replace(/_/g, " ")}
                        </Badge>
                      </TableCell>
                      <TableCell>{getScopeBadge(notification)}</TableCell>
                      <TableCell>
                        <Badge variant={getPriorityBadgeVariant(notification.priority)}>
                          {notification.priority}
                        </Badge>
                      </TableCell>
                      <TableCell>
                        <div className="text-sm">
                          <div>{notification.createdBy.name}</div>
                          <div className="text-muted-foreground">{notification.createdBy.role}</div>
                        </div>
                      </TableCell>
                      <TableCell className="text-sm">
                        {formatDate(notification.createdAt)}
                      </TableCell>
                      <TableCell>
                        <Button
                          variant="ghost"
                          size="icon"
                          onClick={() => {
                            setSelectedNotification(notification);
                            setIsDeleteDialogOpen(true);
                          }}
                        >
                          <Trash2 className="h-4 w-4 text-destructive" />
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}

            {/* Pagination */}
            {pagination.totalPages > 1 && (
              <div className="flex justify-center gap-2 mt-4">
                <Button
                  variant="outline"
                  size="sm"
                  disabled={pagination.page === 1}
                  onClick={() => setPagination(prev => ({ ...prev, page: prev.page - 1 }))}
                >
                  Previous
                </Button>
                <span className="flex items-center px-4 text-sm">
                  Page {pagination.page} of {pagination.totalPages}
                </span>
                <Button
                  variant="outline"
                  size="sm"
                  disabled={pagination.page === pagination.totalPages}
                  onClick={() => setPagination(prev => ({ ...prev, page: prev.page + 1 }))}
                >
                  Next
                </Button>
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Create Notification Dialog */}
      <Dialog open={isCreateDialogOpen} onOpenChange={setIsCreateDialogOpen}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Send className="h-5 w-5" />
              Create Notification
            </DialogTitle>
            <DialogDescription>
              Send a notification to booth agents
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-4">
            {/* Scope Selection - Only L0 can select GLOBAL */}
            <div className="space-y-2">
              <Label>Scope</Label>
              <Select
                value={formData.scope}
                onValueChange={(value: "GLOBAL" | "ACI") => setFormData(prev => ({ ...prev, scope: value }))}
                disabled={!isL0}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {isL0 && <SelectItem value="GLOBAL">Global (All Booth Agents)</SelectItem>}
                  <SelectItem value="ACI">Specific AC</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* AC Selection - Only show if scope is ACI */}
            {formData.scope === "ACI" && (
              <div className="space-y-2">
                <Label>Assembly Constituency</Label>
                <Select
                  value={formData.aci_id}
                  onValueChange={(value) => setFormData(prev => ({ ...prev, aci_id: value }))}
                  disabled={!isL0 && !isL1}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select AC" />
                  </SelectTrigger>
                  <SelectContent>
                    {getAvailableACs().map((ac) => (
                      <SelectItem key={ac.number} value={ac.number.toString()}>
                        {ac.number} - {ac.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            )}

            {/* Type Selection */}
            <div className="space-y-2">
              <Label>Notification Type</Label>
              <Select
                value={formData.type}
                onValueChange={(value) => setFormData(prev => ({ ...prev, type: value }))}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="ANNOUNCEMENT">Announcement</SelectItem>
                  <SelectItem value="ALERT">Alert</SelectItem>
                  <SelectItem value="REMINDER">Reminder</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Priority Selection */}
            <div className="space-y-2">
              <Label>Priority</Label>
              <Select
                value={formData.priority}
                onValueChange={(value) => setFormData(prev => ({ ...prev, priority: value }))}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="low">Low</SelectItem>
                  <SelectItem value="normal">Normal</SelectItem>
                  <SelectItem value="high">High</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Title */}
            <div className="space-y-2">
              <Label>Title</Label>
              <Input
                placeholder="Enter notification title"
                value={formData.title}
                onChange={(e) => setFormData(prev => ({ ...prev, title: e.target.value }))}
                maxLength={100}
              />
              <p className="text-xs text-muted-foreground">{formData.title.length}/100 characters</p>
            </div>

            {/* Message */}
            <div className="space-y-2">
              <Label>Message</Label>
              <Textarea
                placeholder="Enter notification message"
                value={formData.message}
                onChange={(e) => setFormData(prev => ({ ...prev, message: e.target.value }))}
                maxLength={500}
                rows={4}
              />
              <p className="text-xs text-muted-foreground">{formData.message.length}/500 characters</p>
            </div>

            {/* Valid Till (Optional) */}
            <div className="space-y-2">
              <Label>Expires On (Optional)</Label>
              <Input
                type="datetime-local"
                value={formData.validTill}
                onChange={(e) => setFormData(prev => ({ ...prev, validTill: e.target.value }))}
              />
              <p className="text-xs text-muted-foreground">
                Leave empty for no expiration
              </p>
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setIsCreateDialogOpen(false)}>
              Cancel
            </Button>
            <Button onClick={handleCreateNotification} disabled={creating}>
              {creating ? (
                <>
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                  Creating...
                </>
              ) : (
                <>
                  <Send className="h-4 w-4 mr-2" />
                  Send Notification
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <AlertDialog open={isDeleteDialogOpen} onOpenChange={setIsDeleteDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Notification</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete this notification? This action cannot be undone.
              <div className="mt-2 p-3 bg-muted rounded-md">
                <div className="font-medium">{selectedNotification?.title}</div>
                <div className="text-sm text-muted-foreground">{selectedNotification?.message}</div>
              </div>
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction onClick={handleDeleteNotification} className="bg-destructive text-destructive-foreground">
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </DashboardLayout>
  );
};

export default NotificationManagement;
